adding more debugging scripts

diff --git a/scripts/setupRoomScript b/scripts/setupRoomScript
--- a/scripts/setupRoomScript
+++ b/scripts/setupRoomScript
@@ -1,12 +1,22 @@
 #!/bin/bash
 ## don't think this works for mac hostname -I
-LaptopServerIP="152.3.59.21"
 ServerIP="152.3.59.171 152.3.59.187"
 serverRecord="/home/evo14/Desktop/Evo14LocalMirror/RoomInfo/"
 Room=$1
 
+ValidRoomCode="201  206  301A  301B  302A  302B  302C  303  304  305A  305B  306A  306B  306C  402  BalC"
+MatchingCode="=201=206=301A=301B=302A=302B=302C=303=304=305A=305B=306A=306B=306C=402=BalC="
 
 ## TODO make sure ROOM is valid!!
+rr="=${1}="
+if [[ ${MatchingCode} == *${rr}*  ]];
+    then
+    echo "Valid:${rr}"
+else
+    echo "ERROR room code:${rr}"
+fi
+
+exit 3
 IP=`ipconfig getifaddr en0`
 #en1 for wireless
 
@@ -14,8 +24,7 @@ IP=`ipconfig getifaddr en0`
 #["301A"]="152.3.59.2"
 if [ ! -n "${1}" ]
   then 
-    echo "Please provide room code!! Exit script"
-#TODO all list of all possible room
+    echo -e "Error! Please provide a room code!! \nValid room code: ${ValidRoomCode}\nExit script!!!"
     exit 6
 fi
 #ifconfig en0| grep 'inet ' | cut -d: -f2 | awk '{ print $2}'
